### ISSUE TITLE
Script not working on Arch Linux

### ISSUE THREAD

**Issue by ssnailz** [coolst3r/linxboard#1]
Please help
These are the errors
```
> python3 linxboard.py
  File "/home/ssnailz/linxboard/linxboard.py", line 113
    color_dialog = Gtk.ColorChooserDialog(title="Pick a color", parent=window)
    ^
IndentationError: expected an indented block after function definition on line 111
```
```
> python3 archboard\ archived\ version\ 1.py
/home/ssnailz/linxboard/archboard archived version 1.py:3: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Gst, Gdk
Traceback (most recent call last):
  File "/home/ssnailz/linxboard/archboard archived version 1.py", line 57, in <module>
    playbin.set_property("loop", -1)
TypeError: object of type `GstPlayBin' does not have property `loop'

```

**Comment by s-b-repo** [comment]
what distro are you using

**Comment by s-b-repo** [comment]
and the archived versions dont work the only issue is a indeentiostion in the code on line 111

**Comment by s-b-repo** [comment]
> Please help These are the errors
> 
> ```
> > python3 linxboard.py
>   File "/home/ssnailz/linxboard/linxboard.py", line 113
>     color_dialog = Gtk.ColorChooserDialog(title="Pick a color", parent=window)
>     ^
> IndentationError: expected an indented block after function definition on line 111
> ```
> 
> ```
> > python3 archboard\ archived\ version\ 1.py
> /home/ssnailz/linxboard/archboard archived version 1.py:3: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk, GObject, Gst, Gdk
> Traceback (most recent call last):
>   File "/home/ssnailz/linxboard/archboard archived version 1.py", line 57, in <module>
>     playbin.set_property("loop", -1)
> TypeError: object of type `GstPlayBin' does not have property `loop'
> ```

check now

**Comment by ssnailz** [comment]
> what distro are you using

Arch Linux with KDE

>check now

I git cloned again
Now i get this error :(

```
> python3 linxboard.py
  File "/home/ssnailz/linxboard/linxboard.py", line 159
    dialog = Gtk.FileChooserDialog("Import Sound", window,
    ^
IndentationError: expected an indented block after function definition on line 156

```

**Comment by ssnailz** [comment]
ok so i looked up how to fix indentation errors in python and now i get this 

```
> python3 linxboard.py
/home/ssnailz/linxboard/linxboard.py:3: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Gst, Gdk
Traceback (most recent call last):
  File "/home/ssnailz/linxboard/linxboard.py", line 28, in <module>
    button_box = Gtk.ButtonBox(layout=Gtk.ButtonBoxStyle.SPREAD)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/overrides/__init__.py", line 319, in new_init
    return super_init_func(self, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gobject `GtkButtonBox' doesn't support property `layout'

```

:(

**Comment by s-b-repo** [comment]
looks like a init issue cant tell
